--Country
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('1', 'Albania', 'AL')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('2', 'Algeria', 'DZ')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('3', 'Andorra', 'AD')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('4', 'Angola', 'AO')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('5', 'Austria', 'AT')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('6', 'Azerbaijan', 'AZ')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('7', 'Bahrain', 'BH')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('8', 'Belgium', 'BE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('9', 'Benin', 'BJ')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('10', 'Bosnia', 'BA')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('11', 'Brazil', 'BR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('12', 'Bulgaria', 'BG')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('13', 'Burkina Faso', 'BF')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('14', 'Burundi', 'BI')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('15', 'Cameroon', 'CM')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('16', 'Cape Verde', 'CV')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('17', 'Chad', 'TD')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('18', 'Comoros', 'KM')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('19', 'Congo', 'CG')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('20', 'Costa rica', 'CR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('21', 'Croatia', 'HR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('22', 'Cyprus', 'CY')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('23', 'Czechia', 'CZ')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('24', 'Denmark', 'DK')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('25', 'Dominicana', 'DO')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('26', 'Egypt', 'EG')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('27', 'Estonia', 'EE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('28', 'Faroe Islands', 'FO')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('29', 'Finland', 'FI')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('30', 'France', 'FR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('31', 'Gabon', 'GA')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('32', 'Georgia', 'GE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('33', 'Germany', 'DE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('34', 'Gibraltar', 'GI')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('35', 'Greece', 'GR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('36', 'Greenland', 'GL')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('37', 'Guatemala', 'GT')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('38', 'Honduras', 'HN')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('39', 'Hungary', 'HU')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('40', 'Iceland', 'IS')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('41', 'Iran', 'IR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('42', 'Ireland', 'IE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('43', 'Israel', 'IL')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('44', 'Italy', 'IT')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('45', 'Ivory Coast', 'CI')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('46', 'Jordan', 'JO')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('47', 'Kazakhstan', 'KZ')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('48', 'Kuwait', 'KW')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('49', 'Lebanon', 'LB')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('50', 'Liechtenstein', 'LI')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('51', 'Lithuania', 'LT')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('52', 'Luxembourg', 'LU')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('53', 'Macedonia', 'MK')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('54', 'Madagascar', 'MG')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('55', 'Mali', 'ML')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('56', 'Malta', 'MT')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('57', 'Mauritania', 'MR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('58', 'Mauritius', 'MU')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('59', 'Moldova', 'MD')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('60', 'Monaco', 'MA')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('61', 'Montenegro', 'MT')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('62', 'Morocco', 'MC')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('63', 'Mozambique', 'MZ')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('64', 'Netherlands', 'NL')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('65', 'Nicuragua', 'NI')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('66', 'Niger', 'NE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('67', 'Norway', 'NW')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('68', 'Pakistan', 'PK')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('69', 'Poland', 'PL')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('70', 'Palestine', 'PS')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('71', 'Portugal', 'PT')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('72', 'Qatar', 'QA')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('73', 'Kosovo', 'XK')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('74', 'Romania', 'RO')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('75', 'Saint Lucia', 'LC')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('76', 'San Marino', 'SM')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('77', 'Sao Tome Principe', 'ST')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('78', 'Saudi', 'SA')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('79', 'Senegal', 'SN')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('80', 'Seychelles', 'SC')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('81', 'Slovakia', 'SK')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('82', 'Slovenia', 'SI')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('83', 'Spain', 'ES')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('84', 'Sweden', 'SE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('85', 'Switzerland', 'CH')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('86', 'Timor Leste', 'TL')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('87', 'Togo', 'TG')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('88', 'Tunisia', 'TN')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('89', 'Turkey', 'TR')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('90', 'Ukraine', 'UA')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('91', 'UAE', 'AE')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('92', 'UK', 'GB')
INSERT INTO [dbo].[Country] ([CountryID], [CountryName], [CountryCode]) VALUES ('93', 'Virgin Islands', 'VG')

--Account Type
INSERT INTO [dbo].[AccountType] ([AccountTypeID], [AccountTypeName]) VALUES ('1', 'current account')
INSERT INTO [dbo].[AccountType] ([AccountTypeID], [AccountTypeName]) VALUES ('2', 'savings account')
INSERT INTO [dbo].[AccountType] ([AccountTypeID], [AccountTypeName]) VALUES ('3', 'fixed deposit')